<a href="https://colab.research.google.com/github/ElijahKellner/Linear_Algebra_Coding_projects/blob/master/Linear_Algebra_Determinant_Vector_Product_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [15]:
# create the matrix:
A = np.matrix([[10, 7],
               [8, 9]])
 
B = np.matrix([[-10, -1],
               [-4, 7]])

C = np.matrix([[1, -3],
               [7, 7]])


In [17]:
AB=A*B

AB

matrix([[-128,   39],
        [-116,   55]])

In [18]:
BA=B*A
BA

matrix([[-108,  -79],
        [  16,   35]])

In [19]:
np.linalg.det(AB)

-2515.999999999999

In [20]:
np.linalg.det(BA)

-2516.0000000000014

In [22]:
AC=A*C
AC

matrix([[59, 19],
        [71, 39]])

In [23]:
CA=C*A
CA

matrix([[-14, -20],
        [126, 112]])

In [24]:
np.linalg.det(AC)

951.9999999999997

In [25]:
np.linalg.det(CA)

951.9999999999997

In [26]:
BC=B*C
BC

matrix([[-17,  23],
        [ 45,  61]])

In [27]:
CB=C*B
CB

matrix([[  2, -22],
        [-98,  42]])

In [29]:
np.linalg.det(BC)

-2071.9999999999995

In [30]:
np.linalg.det(CB)

-2071.9999999999995

In [31]:
ABC=A*B*C
ABC

matrix([[145, 657],
        [269, 733]])

In [32]:
ACB=A*C*B
ACB

matrix([[-666,   74],
        [-866,  202]])

In [33]:
CBA=C*B*A
CBA

matrix([[-156, -184],
        [-644, -308]])

In [37]:
np.linalg.det(ABC)

-70447.99999999994

In [47]:
D= np.matrix([[3, 2, 3],
               [-6, 1, -10],
              [-8, -9, -9]])

E= np.matrix([[1, -2, 1],
             [5, 5, 4],
             [4, 0, 0]])

F= np.matrix([[1, 0, 0],
             [0, 2, 0],
             [-3, -2, 1]])

In [49]:
DE=D*E
DE

matrix([[ 25,   4,  11],
        [-41,  17,  -2],
        [-89, -29, -44]])

In [50]:
ED=E*D
ED

matrix([[  7,  -9,  14],
        [-47, -21, -71],
        [ 12,   8,  12]])

In [53]:
np.linalg.det(ED)

3067.9999999999973

In [54]:
DF=D*F
DF

matrix([[ -6,  -2,   3],
        [ 24,  22, -10],
        [ 19,   0,  -9]])

In [55]:
FD=F*D
FD

matrix([[  3,   2,   3],
        [-12,   2, -20],
        [ -5, -17,   2]])

In [57]:
np.linalg.det(FD)

-118.00000000000004

In [59]:
EF=E*F
EF

matrix([[-2, -6,  1],
        [-7,  2,  4],
        [ 4,  0,  0]])

In [60]:
FE=F*E
FE

matrix([[  1,  -2,   1],
        [ 10,  10,   8],
        [ -9,  -4, -11]])

In [62]:
np.linalg.det(EF)

-103.99999999999999