<a href="https://colab.research.google.com/github/ElijahKellner/Linear_Algebra_Coding_projects/blob/master/Practice_With_Gram_Schmidt_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [11]:
#Dot product example
np.dot([1, 2], [3, 4])

# How do I find magnitude in np?

np.sqrt(np.dot([1,2], [1, 2]))

2.23606797749979

In [14]:
r1 = [2, 4, 0, 0]
r2 = [1, 2, 3, 6]
r3 = [2, -1, 2, -1]
r4 = [1, 2, 3, 4]

r1

[2, 4, 0, 0]

In [19]:
# Find the first nice basis vector, u1
# 1. pick a new vector
r1
# 2. Subtract the projection of r1 onto the nice basis (u1, u2, u3,...)
#    and save this as a temporary n1
n1=r1
# 3. Find the magnitude of n1
np.sqrt(np.dot(n1, n1))
# 4. Create a nice basis vector    u1 = 1/|n1| * n1
u1= n1/np.sqrt(np.dot(n1, n1))
u1

array([0.4472136 , 0.89442719, 0.        , 0.        ])

In [20]:
# Check that u1 has a magnitude of 1
np.dot(u1, u1)

0.9999999999999999

In [21]:
# Repeat these steps for as many vectors an necessary

In [23]:
# Find the second nice basis vector, u2
# 1. pick a new vector
r2
# 2. Subtract the projection of r2 onto the nice basis (u1, u2, u3,...)
#    and save this as a temporary n2
n2=r2 - np.dot(r2, u1)*u1
# 3. Find the magnitude of n2
np.sqrt(np.dot(n2, n2))
# 4. Create a nice basis vector    u2 = 1/|n2| * n2
u2= n2/np.sqrt(np.dot(n2, n2))
u2

array([0.        , 0.        , 0.4472136 , 0.89442719])

In [28]:
# Find the third nice basis vector, u3
# 1. pick a new vector
r3
# 2. Subtract the projection of r3 onto the nice basis (u1, u2, u3,...)
#    and save this as a temporary n3
n3=r3 - np.dot(r3, u1)*u1 - np.dot(r3, u2)*u2
# 3. Find the magnitude of n3
np.sqrt(np.dot(n3, n3))
# 4. Create a nice basis vector   u3 = 1/|n3| * n3
u3= n3/np.sqrt(np.dot(n3, n3))
u3

array([ 0.63245553, -0.31622777,  0.63245553, -0.31622777])

In [31]:
# Find the fourth nice basis vector, u4
# 1. pick a new vector
r4
# 2. Subtract the projection of r4 onto the nice basis (u1, u2, u3,...)
#    and save this as a temporary n4
n4=r4 - np.dot(r4, u1)*u1 - np.dot(r4, u2)*u2 -np.dot(r4, u3)*u3
# 3. Find the magnitude of n4
np.sqrt(np.dot(n4, n4))
# 4. Create a nice basis vector   u4 = 1/|n4| * n4
u4= n4/np.sqrt(np.dot(n4, n4))
u4

array([-0.63245553,  0.31622777,  0.63245553, -0.31622777])

In [35]:
print(np.dot(u1,u4))
print(np.dot(u2,u4))
print(np.dot(u3,u4))
print(np.dot(u4,u4))

0.0
9.43689570931383e-16
9.71445146547012e-17
0.9999999999999998
